### ISSUE TITLE
TODO List for 1.0 release

### ISSUE THREAD

**Issue by nomadjimbob** [nomadjimbob/mikioplugin#1]
The following is a TODO list for the 1.0 release.

Last updated 09/05/2020 at 6:47pm

---

- [x] Alerts
    - [x] Colour variation
    - [ ] Link colour
    - [x] Dismissible
- [x] Badge
    - [x] Colour variation
    - [x] Pill
    - [ ] Link
- [ ] Breadcrumb
    - [ ] Seperator
- [x] Buttons
    - [x] Colour variation
    - [ ] No text wrap
    - [x] Outline buttons
    - [x] Sizes
    - [x] Block
    - [x] Active
    - [x] Disabled
 - [ ] Button group
    - [ ] Sizes
    - [ ] Vertical
 - [x] Card
    - [x] Title
    - [x] Subtitle
    - [ ] Links
    - [x] Image
    - [ ] List groups with body
    - [x] Header
    - [ ] Footer
    - [ ] Quotes
    - [ ] Text alignment
    - [ ] Link with nav components
    - [ ] Image in footer
    - [ ] Image overlay
    - [ ] Horizontal
    - [ ] Colours
    - [ ] Borders
    - [ ] Card groups
    - [ ] Card decks
    - [ ] Card grids
    - [ ] Card columns
- [x] Carousel
    - [x] Slide
    - [ ] Controls
    - [x] Indicators
    - [x] Captions
    - [x] Crossfade
- [x] Collapse
    - [x] Button support
- [x] Dropdowns
   - [ ] Dropdown items
   - [ ] Colour variation
   - [ ] Sizing
   - [ ] Dropup
   - [ ] Dropright
   - [ ] Dropleft
   - [ ] Dropdown item active
   - [ ] Dropdown item disabled
   - [ ] Alignment
   - [ ] Headers
   - [ ] Dividers
   - [ ] Text
   - Forms (N/A)
- Forms (N/A)
- Input Group (N/A)
- [ ] Jumbotron
- [x] List group
    - [x] List item
    - [ ] List item active
    - [ ] List item disabled
    - [ ] Flush
    - [ ] Horizontal
    - [ ] List item colour variations
    - [ ] List item badges
    - [ ] List item custom content
- Media object (N/A)
- Modal (N/A)
- Navs (N/A?)
- Navbar (N/A)
- [ ] Pagination
    - [ ] Icons
    - [ ] Disabled
    - [ ] Active
    - [ ] Sizing
    - [ ] Alignment
- Popovers (N/A)
- [ ] Progress
    - [ ] Labels
    - [ ] Height
    - [ ] Color variations
    - [ ] Multiple bars
    - [ ] Striped
- ScrollSpy (?)
- Spinners (N/A)
- [ ] Toasts
    - [ ] Position
- [ ] Tooltips on elements?
- [x] Shadow
